version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 13000:3000
    volumes:
      - .:/app
    tty: true
    command: bash -c "rm -f ./tmp/pids/server.pid && ./bin/dev"
