Muscle.create([
  { name: "カーフ", code: "calf" },
  { name: "ハムストリング", code: "hamstring" },
  { name: "大腿四頭筋", code: "quadriceps" },
  { name: "臀筋", code: "gluteus" },
  { name: "腸腰筋", code: "iliopsoas" },
  { name: "内転筋", code: "adductor" },
  { name: "腹直筋", code: "rectus_abdominis" },
  { name: "腹斜筋", code: "obliques" },
  { name: "脊柱起立筋", code: "erector_spinae" },
  { name: "前腕", code: "forearm" },
  { name: "上腕二頭筋", code: "biceps" },
  { name: "上腕三頭筋", code: "triceps" },
  { name: "三角筋前部", code: "front_deltoid" },
  { name: "三角筋中部", code: "lateral_deltoid" },
  { name: "三角筋後部", code: "rear_deltoid" },
  { name: "ローテーターカフ", code: "rotator_cuff" },
  { name: "大胸筋下部", code: "lower_chest" },
  { name: "大胸筋中部", code: "middle_chest" },
  { name: "大胸筋上部", code: "upper_chest" },
  { name: "広背筋下部", code: "lower_latissimus_dorsi" },
  { name: "広背筋上部", code: "upper_latissimus_dorsi" },
  { name: "僧帽筋下部", code: "lower_trapezius" },
  { name: "僧帽筋中部", code: "middle_trapezius" },
  { name: "僧帽筋上部", code: "upper_trapezius" },
])
